'use client';
import { ArrowUpRight, Check, HelpCircle } from 'lucide-react';
import { addOns, companyTypes, copy, faqs, Lang, packages, steps, why } from '@/data/content';
import { packageMessage, whatsappLink } from '@/lib/whatsapp';

export function TrustStrip({lang}:{lang:Lang}){return <section className="mx-auto max-w-6xl px-4"><div className="grid gap-3 rounded-[30px] bg-white p-4 shadow-soft md:grid-cols-4">{copy[lang].trust.map(t=><div key={t} className="rounded-2xl bg-lavender/60 p-4 text-center text-sm font-bold text-ink/75">{t}</div>)}</div></section>}
export function CompanyTypes({lang}:{lang:Lang}){const c=copy[lang];return <section id="types" className="mx-auto max-w-7xl px-4 py-24" dir={lang==='ar'?'rtl':'ltr'}><div className="mx-auto max-w-3xl text-center"><h2 className="text-4xl font-black">{c.companyTitle}</h2><p className="mt-4 text-ink/60">{c.companyText}</p></div><div className="mt-12 grid gap-5 md:grid-cols-4">{companyTypes.map(t=><div key={t.key} className="card-hover rounded-[30px] border border-violet-100 bg-white p-6"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet text-white font-black">{t.key[0]}</div><h3 className="mt-5 text-2xl font-black">{t.key}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-ink/60">{lang==='en'?t.en:t.ar}</p><a href={whatsappLink(packageMessage(undefined,t.key))} className="mt-6 inline-flex items-center gap-2 font-bold text-violet">{c.cta}<ArrowUpRight size={16}/></a></div>)}</div></section>}
export function HowItWorks({lang}:{lang:Lang}){return <section id="how" className="bg-white py-24" dir={lang==='ar'?'rtl':'ltr'}><div className="mx-auto max-w-7xl px-4"><h2 className="text-center text-4xl font-black">{copy[lang].howTitle}</h2><div className="mt-12 grid gap-5 md:grid-cols-4">{steps.map((s,i)=><div key={i} className="rounded-[30px] bg-gradient-to-br from-lavender to-white p-6 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-full bg-violet text-white font-black">{i+1}</div><p className="mt-6 text-xl font-black">{lang==='en'?s.en:s.ar}</p></div>)}</div></div></section>}
export function Pricing({lang}:{lang:Lang}){const c=copy[lang];return <section id="pricing" className="mx-auto max-w-7xl px-4 py-24" dir={lang==='ar'?'rtl':'ltr'}><div className="text-center"><h2 className="text-4xl font-black">{c.pricingTitle}</h2><p className="mx-auto mt-4 max-w-2xl text-ink/60">{c.pricingText}</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{packages.map(p=><div key={p.name} className={`card-hover relative rounded-[34px] p-7 ${p.popular?'bg-violet text-white shadow-soft':'bg-white text-ink border border-violet-100'}`}>{p.popular&&<span className="absolute right-6 top-6 rounded-full bg-white px-3 py-1 text-xs font-black text-violet">Most Popular</span>}<h3 className="text-2xl font-black">{p.name}</h3><p className={`mt-3 min-h-12 text-sm ${p.popular?'text-white/75':'text-ink/60'}`}>{lang==='en'?p.en:p.ar}</p><div className="mt-6 text-5xl font-black">{p.price}</div><ul className="mt-7 space-y-3">{(lang==='en'?p.featuresEn:p.featuresAr).map(f=><li key={f} className="flex gap-3 text-sm"><Check size={18}/><span>{f}</span></li>)}</ul><a href={whatsappLink(packageMessage(p.name))} className={`mt-8 flex justify-center rounded-full px-5 py-4 font-bold ${p.popular?'bg-white text-violet':'bg-violet text-white'}`}>{c.cta}</a></div>)}</div></section>}
export function AddOns({lang}:{lang:Lang}){return <section id="services" className="bg-white py-24" dir={lang==='ar'?'rtl':'ltr'}><div className="mx-auto max-w-7xl px-4"><h2 className="text-center text-4xl font-black">{copy[lang].addTitle}</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{addOns.map((a,i)=><div key={i} className="rounded-[26px] border border-violet-100 bg-lavender/30 p-6 font-bold">{lang==='en'?a[0]:a[1]}</div>)}</div></div></section>}
export function WhyUs({lang}:{lang:Lang}){return <section className="mx-auto max-w-7xl px-4 py-24" dir={lang==='ar'?'rtl':'ltr'}><h2 className="text-center text-4xl font-black">{copy[lang].whyTitle}</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{why.map((w,i)=><div key={i} className="rounded-[30px] bg-white p-8 shadow-soft"><h3 className="text-2xl font-black">{w[0]}</h3><p className="mt-3 text-ink/60">{w[1]}</p></div>)}</div></section>}
export function FAQ({lang}:{lang:Lang}){return <section id="faq" className="bg-white py-24" dir={lang==='ar'?'rtl':'ltr'}><div className="mx-auto max-w-4xl px-4"><h2 className="text-center text-4xl font-black">{copy[lang].faqTitle}</h2><div className="mt-10 space-y-4">{faqs.map((f,i)=><details key={i} className="rounded-[24px] border border-violet-100 p-6"><summary className="flex cursor-pointer items-center gap-3 font-black"><HelpCircle size={18}/>{lang==='en'?f[0]:f[2]}</summary><p className="mt-4 text-ink/60">{lang==='en'?f[1]:f[3]}</p></details>)}</div><p className="mt-8 rounded-2xl bg-lavender/70 p-5 text-center text-sm text-ink/70">{copy[lang].disclaimer}</p></div></section>}
export function FinalCTA({lang}:{lang:Lang}){const c=copy[lang];return <section className="px-4 py-24" dir={lang==='ar'?'rtl':'ltr'}><div className="mx-auto max-w-5xl rounded-[40px] bg-violet p-10 text-center text-white shadow-soft md:p-16"><h2 className="text-4xl font-black">{c.finalTitle}</h2><p className="mx-auto mt-4 max-w-xl text-white/75">{c.finalText}</p><a href={whatsappLink(packageMessage())} className="mt-8 inline-flex rounded-full bg-white px-8 py-4 font-black text-violet">{c.cta}</a></div></section>}
